[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
via_ir = true
solc_version = "0.8.28"

[fmt]
sort_imports = true
auto_detect_license = true

[doc]
src = "contracts"
title = "Every Protocol â€“ Periphery"
repository = "https://github.com/everyprotocol/periphery"
book = "./docs/additional.toml"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
